CREATE TABLE "Nashville Housing" (
UniqueID varchar(5),
ParcelID varchar(16),
LandUse varchar,
PropertyAddress varchar,
SaleDate date,
SalePrice varchar,
LegalReference varchar,
SoldAsVacant varchar(3),
OwnerName varchar,
OwnerAddress varchar,
Acreage float,
TaxDistrict varchar,
LandValue INT,
BuildingValue INT,
TotalValue INT,
YearBuilt varchar(4),
Bedrooms varchar(2),
FullBath varchar(2),
HalfBath varchar(1)
);
